[package]
authors = ["Ballerina"]
distribution = "2201.10.2"
export = ["FhirAuditService"]
keywords = ["Healthcare", "Audit", "Prebuilt", "Service"]
name = "FhirAuditService"
org = "wso2"
version = "1.0.0"

[build-options]
observabilityIncluded = true
